AllCops:
  Exclude:
    - bin/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
